appname: WeightTracker
layout: main
charset: UTF-8
template: template_toolkit
logger: console
log: core
warnings: 1
show_errors: 1
startup_info: 1

plugins:
  DBIC:
    default:
      schema_class: WeightTracker::Schema
      options:
        quote_char: '"'
        name_sep: .
